### ISSUE TITLE
questions regarding your fork

### ISSUE THREAD

**Issue by stepir** [simont77/homebridge-myhome#1]
Hi Simone, 

I've noticed your work on this plugin and leveraged portion of your code to adapt Agenlo's one to my need/setup as well. Thanks!

I've noticed a lot of your work is focused also on EVE (which I dont have) integration with MyHome (that I'm using as well) - so wanted to ask you some questions:

1) MHPowerMeter. Is this the BTicino one or an EVE accessory? I have a F521 (energy metering and load control) used also to measure consumption (I can get it display on my home touchscreens and in the official my home apps), but I cannot get it working with homebridge. The accessory is just ignored at homebridge startup. The address format shown in Angelo documentation is "0/6/3" while my device have a single digit address "2". Thoughts?

2) MHAlarm. Is this the BTicino one? Is the code already functional/implemented? I could not understand the configuration parameters to be used in the config.js - I have a BTicino 3500 unit and wondering if it might work

3) MHAux.  Is the code already functional/implemented?  I haven't tested it this one yet.

Thanks!

**Comment by simont77** [comment]
Hi, it's all BTicino and all my additions respect to Angelo's code are functional. The PowerMeter is using the old F421 that I believe has different OpenWeb frames compared to the F521. MHAlarm is using 3486, zone activation is hard-coded into the plugin based on my installation.

Use in config.json, for AUX
```
accessory": "MHAux",
"name": "Fuga gas",
"address": "1",
"type": "Gas"
```

for Alarm:
```
"accessory": "MHAlarm",
"name": "Antifurto"
```

for PowerMeter
```
"accessory": "MHPowerMeter",
"name": "Consumo",
"refresh": 10
```

**Comment by simont77** [comment]
The integration is not with Eve accessories, but with Eve.app. It's much better than Home.app in supporting unofficial accessories, and for some of them it has a nice history feature that I implemented as well.

**Comment by stepir** [comment]
Thanks Simone, got it now!

Where do you specify the PowerMeter address then?

**Comment by simont77** [comment]
With the old F421 there is no address. You have a central unit that measures total power, and then controlled loads with priority.

**Comment by stepir** [comment]
that's why - thanks for clarifying. Can I ask you where are you from and if you'd be interested in a professional engagement regarding this project? if you prefer discuss this offline you can reach me at stepir [at] yahoo dot com

Stefano

**Comment by simont77** [comment]
I’m from Italy. Thanks for your proposal, but I’m already full-time employed. This is an hobby for me.
