### ISSUE TITLE
Publish on npm ?

### ISSUE THREAD

**Issue by LeJeko** [simont77/homebridge-myhome#3]
Hello,
First of all thank you for your work.
I installed your plugin at a friend's house but it is very difficult to navigate among all these myhome forks ... even for a developer ... but I think I found the right one!

Now that Homebridge has a nice interface for installing plugins, why not publish your fork on npm so you can install it directly?

Because currently there is a lot of confusion when looking for myhome and even more after the manual installation which indicates @ juliensantos87 and the npm link refers to "lockitron" ...
![Capture d’écran 2020-09-24 à 00 10 19](https://user-images.githubusercontent.com/13176530/94081936-168cc200-fe00-11ea-96f5-20894d784fe5.png)

If @ juliensantos87 does not release the name homebridge-myhome on npm, you might as well create a new one: homebridge-myhome-own for example.

This will make life easier for many users!

**Comment by simont77** [comment]
Thanks. I know I can publish it on npm, unfortunately this plugin is strongly customized on my installation and I don't have enough time to make it suitable for publishing nor for giving support. So I prefer to leave it here only. 

In any case you can install it using "npm install simont77/homebridge-myhome", if you want.

**Comment by LeJeko** [comment]
I understand no worries!
But since it took me over a year to get it working, I'm going to release a new version that's easy to find and implement.

In addition, I would like to add the management of the position of the roller blinds in real time as I implemented it for the homebridge-ewelink plugin.

Your fork apparently works well at my friend's house so could you explain your customization a bit please?

Subsidiary question, I'm starting with Bticino but after 150 commits you might be able to help me:
My friend owns an F453. Do you know if an F454 could stream video from a C300X? I would like to try to implement a doorbell.

**Comment by simont77** [comment]
The Alarm zones are customized on my installation and hardcoded. 
For load control and power reading I used the old protocol, that is incompatible with the newer one, probably you will have to rewrite it completely.
Blinds are only for the original one, with no position info.
Motion and contact sensors are actually alarm sensors, so they are not on the automation bus and use instead AUX signal.
Thermostat and temp sensors are untested and carried out from the original code (I don’t have any thermo device).

Unfortunately I don’t have any AV device, so I cannot help you with the video stream. You should find the commands on the OpenWebNet documentation.

**Comment by LeJeko** [comment]
Thank you for sharing.
No more Alarm nor power/load in my case. Thermostat appears to be irrelevant.
For blinds, I managed them with a Sonoff dual switch without any position info.
I've found url in WHO=7 : http://IPaddress/telecamera.php?CAM_PASSWD=password

**Comment by bubez81** [comment]
hello simont77 I know that the thermostats (99-zone) works great, the only thing that can really be useful is the single thermostat implementation, I have 4 single heat thermostats, but I'm not good enough to implement them.
If you want to try I can be your lab rat

**Comment by simont77** [comment]
Sorry, but I really don't have time to follow this project. Should not be so difficult to move from 99 to 4 zone using the OpenWebNet documentation for the commands

**Comment by bubez81** [comment]
ok I'll give it a try can you please link me the right url? I can't find it on the Bticino site

**Comment by bubez81** [comment]
(it's not the 4 zone is the single zone I think)

**Comment by simont77** [comment]
https://developer.legrand.com/documentation/open-web-net-for-myhome/

**Comment by simont77** [comment]
Should be WHO=4

**Comment by bubez81** [comment]
thank you!!
