### ISSUE TITLE
Use F411/4 channel as momentary switch

### ISSUE THREAD

**Issue by EdoFede** [simont77/homebridge-myhome#5]
Ciao,

ho configurato homebridge-myhome, ma non riesco a trovare il modo per inviare un impulso su un canale di un F411/4.

Su un canale ho collegato il motore della serranda del garage (tramite un relè che chiude il contatto di comando quando viene alimentato dal F411/4).
Su Myhome_Up ho configurato l'oggetto "serratura" ed i due comandi in modalità "ON temporizzato" con un tempo di 0.5 secondi.
Quindi quando premo uno dei due comandi (oppure controllo dall'app), viene acceso e spento (dopo 0.5 secondi) il canale corrispondente.

C'è modo di ottenere lo stesso comportamento con il tuo plugin?
Ho tentato di usare MHBlind ma non fa assolutamente nulla, tranne rimanere in attesa.
Con MHRelay funziona, ma solo in modalità latch (devo accendere e poi spegnere manualmente).

Grazie in anticipo!

**Comment by simont77** [comment]
MHBlind funziona solo per attuatori configurati come interbloccati per tapparelle. Se ti funziona correttamente con MHRelay vuol dire che li hai configurati come interruttori indipendenti. Se li puoi temporizzati prova a usare MHTimedRelay, oppure configura la temporizzazione direttamente sull’attuatore.

**Comment by EdoFede** [comment]
Giusto, mi era sfuggito nella descrizione!  :-)
Funziona perfettamente.

Grazie mille e complimenti per il lavoro!
